version: "3"

services:
  # Frontend
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: mutcompute:client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    command: yarn start


  # Backend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mutcompute:backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/app/
      - ./data:/app/data
    environment:
      SES_EMAIL_HOST: ${SES_EMAIL_HOST}
      SES_EMAIL_PORT: ${SES_EMAIL_PORT}
      SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
      SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
      DB_URI: ${DB_URI_BACKEND}
      HOSTNAME: ${HOSTNAME}
      PORT: ${PORT}
    depends_on:
      - nn_api
    command: gunicorn -b 0.0.0.0:5000 api:app
    # entrypoint: python /app/api.py


  # nn_api:
  #   container_name: nn_api
  #   build:
  #     context: ./nets
  #     dockerfile: Dockerfile
  #   image: mutcompute:api
  #   volumes: 
  #     - ./nets:/mutcompute_2020
  #     - ./data:/mutcompute_2020/data
  #   environment:
  #     PYTHONUNBUFFERED: 1
  #     PYTHONPATH: /mutcompute_2020:/mutcompute_2020/mutcompute
  #     DB_URI: ${DB_URI_NN_API}
  #     DB_NN_TABLE: ${DB_NN_TABLE}
  #   depends_on:
  #     - redis 
  #     - celery
  #   ports:
  #     - 8000
  #   working_dir: /mutcompute_2020/api
  #   entrypoint: python api.py


  # # #Queue/Worker Processes
  # celery:
  #   container_name: celery
  #   build:
  #     context: ./nets
  #     dockerfile: Dockerfile
  #   image: mutcompute:api
  #   volumes: 
  #     - ./nets:/mutcompute_2020
  #     - ./data:/mutcompute_2020/data
  #   environment:
  #     PYTHONUNBUFFERED: 1
  #     PYTHONPATH: /mutcompute_2020:/mutcompute_2020/mutcompute
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #     CELERY_RESULT_BACKEND: redis://redis:6379/0
  #     SES_EMAIL_HOST: ${SES_EMAIL_HOST}
  #     SES_EMAIL_PORT: ${SES_EMAIL_PORT}
  #     SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
  #     SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
  #     DB_URI: ${DB_URI_NN_API}
  #     DB_NN_TABLE: ${DB_NN_TABLE}
  #     HOSTNAME: ${HOSTNAME}
  #     PORT: ${PORT}
  #   working_dir: /mutcompute_2020/api
  #   entrypoint: celery -A task.celery worker -l debug --concurrency 2 
  #   # entrypoint: celery -A task.celery worker --loglevel=DEBUG --concurrency 2 -P solo
  #   depends_on:
  #     - redis 


  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   hostname: redis
  #   ports:
  #     - 6379 


  # # # Reverse Proxy
  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx/nginx_ssl.conf:/etc/nginx/conf.d/default.conf 
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/www:/var/www/certbot
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # # SSL certificates
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  # # flower:
  # #     container_name: FLOWER
  # #     image: mher/flower
  # #     command: flower --broker=redis://redis:6379/0 --port=8888
  # #     ports:
  # #       - 9181:8888
  # #     depends_on: 
  # #       - celery
  

      